import '../../public/assets/css/master.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import AudioPlayer from '@/components/audio-player/audio-player';
import Playlist from '@/components/audio-player/playlist';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header />
      {children}
      <Footer />
      <AudioPlayer />
      <Playlist />
      </body>
    </html>
  )
}
