import '@/styles/master.scss';
import Header from '@/components/header/header';
import Footer from '@/components/footer';
import AudioPlayer from '@/components/audio-player/audio-player';
import Playlist from '@/components/audio-player/playlist';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main style={{minHeight: 'calc(100vh - 58px)'}}>
          {children}
        </main>
        <Footer />
        <AudioPlayer />
        <Playlist />
      </body>
    </html>
  )
}
