# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#  workflow_dispatch:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.20.2]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: FTP deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
       server: testernest.ru
       username: u0545248_github
       password: ${{ secrets.ftp_password }}

#    - name: ssh deploy on my server
#      uses: easingthemes/ssh-deploy@v2.1.4
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_PROD }}
#        REMOTE_HOST: ${{ secrets.DEPLOY_HOST_PROD }}
#        REMOTE_USER: ${{ secrets.DEPLOY_USER_PROD }}
#        REMOTE_PORT: ${{ secrets.DEPLOY_PORT_PROD }}
#        SOURCE: "build/"
        # TARGET: ${{ secrets.DEPLOY_TARGET_PROD }}
